name: C/C++ CI

on:
  push:
    branches: [ "wp" ]
  pull_request:
    branches: [ "wp" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: CI Build
      run: chmod +x ci-build-debug.sh && ./ci-build-debug.sh

    - uses: actions/upload-artifact@v3
      with:
        name: Galaxy S5 Mini Duos
        path: ./workspace/bootpayload.bin
